name: Generate snake and pacman animations

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12 horas
  workflow_dispatch:        # permite rodar manualmente
  push:
    branches:
      - master
      - main

jobs:
  generate_snake:
    name: Generate Snake Animation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  generate_pacman:
    name: Generate Pacman Animation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug before generation
        run: |
          echo "Before running the Pacman action"
          pwd
          ls -la

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Debug after generation
        run: |
          echo "After running the Pacman action"
          pwd
          ls -la
          find . -type f

      - name: Move pacman SVG to dist folder
        run: |
          mkdir -p dist
          find . -name "*.svg" -exec cp {} dist/ \;

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
